### PR TITLE
Add client_key argument

### PR DESCRIPTION
**Pull request by Cyr-ius**

### CODE REVIEW

**Comment by Cyr-ius** [comment]
Like asking I just pushed the PR.
If we can get a new version in pypi, I'm up for it.
Because I want to deliver a new version of LG Webos TV component for Home Assistant. and suddenly I could directly include the new version.

**Comment by bendavid** [comment]
Are you planning to use this feature to bypass the use of the config file in Home Assistant?

**Comment by Cyr-ius** [comment]
> Are you planning to use this feature to bypass the use of the config file in Home Assistant?

Yes quite.
I created an integration via the HA configuration flow and the goal is to do without the file, however I need a new version in pypi to use it from HomeAssistant
Currently the version used is aiopylgtv (0.3.3)

**Comment by bendavid** [comment]
0.4.0 is on pypi now which should also skip the config file entirely if a key is provided at initialization

**Comment by Cyr-ius** [comment]
> 0.4.0 is on pypi now which should also skip the config file entirely if a key is provided at initialization

I have just included the new version in the evolutions of Home Assistant that I am preparing.
I hadn't seen it, but no matter what, you still generate the file (line 201). I generate it in / tmp because it is no longer useful.
We should have found a solution to avoid creating it.

**Pull request merged**
